print("==================================================")
print("                Masukkan Data Anda                ")
print("==================================================")
mai
# list data
Nama_Lengkap        = input("1. Nama Lengkap            : ")
Umur                = input("2. Umur                    : ")
asal_kota           = input("3. Asal Kota               : ")
domisili            = input("4. domisili                : ")
tempat_lahir        = input("5. Pengalaman Kerja        : ")
Pendidikan_Terakhir = input("6. Pendidikan Terakhir     : ")
Jenis_Kelamin       = input("7. Keahlian Teknis         : ")
Role                = input("8. role                    : ")
Proyek_Terbesar     = input("9. Proyek Terbesar         : ")
Sertifikasi         = input("10. Sertifikasi            : ")
Hobi                = input("11. Hobi                   : ")
Bahasa_Dikuasai     = input("12. Bahasa yang Dikuasai   : ")
Kewarganegaraan     = input("13. Kewarganegaraan        : ")
instagram           = input("14. Username Instagram     : ")
Email               = input("15. Email                  : ")
Nomor_Telepon       = input("16. Nomor Telepon          : ")
LinkedIn            = input("17. LinkedIn Profile       : ")
Github              = input("18. Github Profile         : ")
Cita_Cita           = input("20. Cita-Cita              : ")
Universitas         = input("20. Universitas            : ")

# Menampilkan data dengan format rapi
print("\n========== Data Anda ==========")
print("Nama Lengkap           : " + Nama_Lengkap)
print("Umur                   : " + Umur)
print("Asal Kota              : " + asal_kota)
print("domisili               : " + domisili)
print("Tempat lahir           : " + tempat_lahir)
print("Pendidikan Terakhir    : " + Pendidikan_Terakhir)
print("Role                   : " + Role)
print("Proyek Terbesar        : " + Proyek_Terbesar)
print("Sertifikasi            : " + Sertifikasi)
print("Hobi                   : " + Hobi)
print("Bahasa yang Dikuasai   : " + Bahasa_Dikuasai)
print("Kewarganegaraan        : " + Kewarganegaraan)
print("Instagram              : " + instagram)
print("Email                  : " + Email)
print("Nomor Telepon          : " + Nomor_Telepon)
print("LinkedIn Profile       : " + LinkedIn)
print("Github Profile         : " + Github)
print("Cita-Cita              : " + Cita_Cita)
print("===================================")
print(" Terima kasih telah mengisi data diri Anda!")
print("===================================\n")


print("Hallo teman teman kenalin nih, Namaku ",Nama_Lengkap,
    " Umur aku masi balita ko, contohnya ",Umur,
    " tahun hehe \n, Asal aku dari bumi bagian barat, tau kan dimana?? Yap di ",
    asal_kota ,"\n tapi sekarang lagi di kota yang selalu ada cerita ",domisili,"🫢🫢.")
print("----------------------------------")

